const areaTriangulo = (base, altura) => (base * altura) / 2;
const perimetroEquilatero = (lado) => 3 * lado;
const perimetroIsosceles = (ladoIgual, base) => 2 * ladoIgual + base;
const perimetroEscaleno = (lado1, lado2, lado3) => lado1 + lado2 + lado3;
const areaCuadrado = (lado) => lado * lado;
const perimetroCuadrado = (lado) => 4 * lado;
const areaRectangulo = (base, altura) => base * altura;
const perimetroRectangulo = (base, altura) => 2 * (base + altura);
const areaCirculo = (radio) => Math.PI * radio * radio;
const longitudCircunferencia = (radio) => 2 * Math.PI * radio;
